/**
 * Created by baysao on 21/02/2016.
 */
var VBX_VERSION = 185;
var VBX_LAYOUT_NAME = 'jolt';
function getPlayerConfigurations() {
    return {
        "affiliateRegex": ["greensmoke\\.co.+?\\/aff\\/(?P<ac>\\d+)\\/ad\\/(?P<aid>\\d+)", "tplclick\\?lid=\\d+&pubid=(?P<ac>.+)", "bin/.+?\\?id=(?P<ac>[^&]+)&offerid=(?P<aid>[^&]+)|bin/.+?\\?id=(?P<ac>.+?)&", "&pubid=(?P<ac>[^&]*)", "&aid=(?P<aid>[\\d\\.]+)&pid=(?P<ac>\\d+)&", "/click-(?P<ac>\\d+)-(?P<aid>[\\d\\.]+)", "shareasale\\.com[^?]*\\?(?P<query>.*)", "/t/\\d+-\\d+-(?P<ac>\\d+)-\\d+", "linkconnector\\.com[^?]*\\?(?P<query>.*)", "(?:/BI/(?P<ac>\\d+)/KBID/(?P<aid>\\d+))|(?:BI=(?P<ac>\\d+).+?KBID=(?P<aid>\\d+))"],
        "deleted": false,
        "locked": false,
        "ctaLink": "http://vinamilk.com.vn",
        "videoEmailUrl": "",
        "ctaApps": "",
        "ctaButtonBackgroundColor": "16763904",
        "captions": "",
        "customLogoLink": "http://saobacdau.vn",
        "showQualityButton": "false",
        "showTwitterButton": "true",
        "bannerApps": "",
        "customLogoUrl": "//assets.viewbix.com/66b0c3c9da695e5d5a10dd469fa14bbf.png",
        "showShareButton": "true",
        "showFacebookButton": "true",
        "midRollApps": "",
        "bottomLogoUrl": "",
        "ctaText": "Liên Hệ",
        "preRollApps": "",
        "facebookSharePageUrl": "",
        "tinyUrl": "http://tinyurl.com/hh6j6t7",
        "titleTextFormatColor": "0xFFFFFF",
        "customCss": "",
        "defaultTwitterMessage": "Check out this video for {title}: {link}",
        "bottomLogoLink": "",
        "fbConversionPixel": "",
        "keepControlsVisible": "false",
        "videoThumbnailUrl": "//assets.viewbix.com/bef4b4f841950e9306a22c4914de07a0.jpg",
        "showHideUi": "",
        "postRollApps": "",
        "showViewbixBranding": "false",
        "standardTextFormatFont": "Arial",
        "videoLink": "",
        "useYouTubeHighQuality": "false",
        "videoUrl": "http://demo.easyvideo.vn/vinamilk.mp4",
        "detailsAppId": "7b5bea38-76df-4e26-8462-22356a28eafd",
        "openvvTrackScriptUrl": "",
        "ctaButtonButtonTextFormatColor": "0x000000",
        "title": "Vinamilk Optimum 4",
        "scaleLogoToTitleBar": "true",
        "playVideoInApps": "false",
        "applications": [{
            "id": "7b5bea38-76df-4e26-8462-22356a28eafd",
            "internalId": "2775c698-6307-4565-9446-dbdf3037c616",
            "component": "com.qoof.sdk.components.rss.RSSItem",
            "order": 1,
            "thumbnailWidth": "70",
            "label": "About",
            "showInMenu": "true",
            "feedXmlString": "<feed><entry><id></id><title>Quảng Cáo Vinamilk Trung Thu Vui nhộn dành cho bé 2015</title><content>Nguồn :https://www.youtube.com/watch?v=rWg4fhE0XA0\nhttps://www.youtube.com/watch?v=Ov_tzqOIy10\nhttps://www.youtube.com/watch?v=3Wr2JqayI3w\nhttps://www.youtube.com/watch?v=7t2TCZIjIDg\nhttps://www.youtube.com/watch?v=fJfRHkE9G-I</content><thumbnailUrl></thumbnailUrl><link></link><contentSnippet>Nguồn :https://www.youtube.com/watch?v=rWg4fhE0XA0\nhttps://www.youtube.com/watch?v=Ov_tzqOIy10\nhttps://www.youtube.com/watch?v=3Wr2JqayI3w\nhttps://www.youtube.com/watch?v=7t2TCZIjIDg\nhttps://www.youtube.com/watch?v=fJfRHkE9G-I</contentSnippet><publishedDate></publishedDate><index>1</index><autoGen>true</autoGen></entry></feed>",
            "icon": "/storage/content/icon/16/details.png"
        }, {
            "id": "f726ccd7-0dd8-4160-a86f-5b966b9dd0de",
            "internalId": "cd6315ae-5cd2-41cf-8dd9-a4024ac290ab",
            "component": "com.qoof.sdk.components.forms.MailForm",
            "order": 2,
            "instructions": "Please fill in the form below and click \"Submit\".",
            "includeComments": "false",
            "checkboxLabel": "Add me to list",
            "icon": "/storage/content/icon/16/mail.png",
            "from": "viewbix-lead@viewbix.com",
            "label": "Mail Form",
            "emails": "vutt@saobacdau.vn",
            "commentsLabel": "Comments",
            "showInMenu": "true",
            "success": "Thank you for contacting us.",
            "submitText": "Submit",
            "includeCheckbox": "false"
        }],
        "playerId": "baeb23a9-e9f0-420a-ac33-c1074a8e5be3",
        "memberId": "ffb8a5fd-6ea7-4ce6-bcc1-9c2b2254898d"
    };
}
