var VBX_VERSION = [[[= model.vbxversion]]];
var VBX_LAYOUT_NAME = 'jolt';
//{
//            "id": "5b279456-05bd-40cd-9963-758c5aad8989",
//            "internalId": "dfc72dfb-6f3d-4945-b7ef-e54a82d856be",
//            "component": "com.qoof.sdk.components.rss.RSSItem",
//            "order": 0,
//            "mid_roll_app.startTime": "29",
//            "thumbnailWidth": "190",
//            "feedXmlString": "<feed><entry><id></id><title>ĐIỆN THOẠI SAMSUNG GALAXY S6 EDGE 32GB</title><content>Màn hình:\tSuper AMOLED, 5.1&quot;, Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 &amp; 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</content><thumbnailUrl></thumbnailUrl><link></link><contentSnippet>Màn hình:\tSuper AMOLED, 5.1&quot;, Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 &amp; 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</contentSnippet><publishedDate></publishedDate><index></index></entry></feed>",
//            "showInMenu": "true",
//            "icon": "/storage/content/icon/16/details.png",
//            "label": "Thông tin sản phẩm"
//        }
//function getAppConfigs() {
//    return {
//        "id": "5b279456-05bd-40cd-9963-758c5aad8989",
//        "internalId": "dfc72dfb-6f3d-4945-b7ef-e54a82d856be",
//        "component": "com.qoof.sdk.components.rss.RSSItem",
//        "order": 0,
//        "lightStyle": false,
//        "mid_roll_app.startTime": "29",
//        "feedXmlString": "<feed><entry><id></id><title>ĐIỆN THOẠI SAMSUNG GALAXY S6 EDGE 32GB</title><content>Màn hình:\tSuper AMOLED, 5.1&quot;, Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 &amp; 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</content><thumbnailUrl></thumbnailUrl><link></link><contentSnippet>Màn hình:\tSuper AMOLED, 5.1&quot;, Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 &amp; 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</contentSnippet><publishedDate></publishedDate><index></index></entry></feed>",
//        "icon": "/storage/content/icon/16/details.png",
//        "thumbnailWidth": "190",
//        "showInMenu": "true",
//        "label": "Thông tin sản phẩm",
//        "player.videoThumbnailUrl": "//assets.viewbix.com/4dc78442-b3ce-446a-aaf7-92c3c452b4b2.jpg",
//        "player.title": "Samsung Galaxy S6 edge+ : Official Introduction",
//        "player.videoUrl": "http://demo.easyvideo.vn/samsung_s6e.mp4",
//        "player.name": "Samsung Galaxy S6 edge+ : Official Introduction",
//        "affiliateRegex": ["greensmoke\\.co.+?\\/aff\\/(?P<ac>\\d+)\\/ad\\/(?P<aid>\\d+)", "tplclick\\?lid=\\d+&pubid=(?P<ac>.+)", "bin/.+?\\?id=(?P<ac>[^&]+)&offerid=(?P<aid>[^&]+)|bin/.+?\\?id=(?P<ac>.+?)&", "&pubid=(?P<ac>[^&]*)", "&aid=(?P<aid>[\\d\\.]+)&pid=(?P<ac>\\d+)&", "/click-(?P<ac>\\d+)-(?P<aid>[\\d\\.]+)", "shareasale\\.com[^?]*\\?(?P<query>.*)", "/t/\\d+-\\d+-(?P<ac>\\d+)-\\d+", "linkconnector\\.com[^?]*\\?(?P<query>.*)", "(?:/BI/(?P<ac>\\d+)/KBID/(?P<aid>\\d+))|(?:BI=(?P<ac>\\d+).+?KBID=(?P<aid>\\d+))"]
//    };
//}
//function getPlayerConfigurations() {
//    return {
//        "affiliateRegex": ["greensmoke\\.co.+?\\/aff\\/(?P<ac>\\d+)\\/ad\\/(?P<aid>\\d+)", "tplclick\\?lid=\\d+&pubid=(?P<ac>.+)", "bin/.+?\\?id=(?P<ac>[^&]+)&offerid=(?P<aid>[^&]+)|bin/.+?\\?id=(?P<ac>.+?)&", "&pubid=(?P<ac>[^&]*)", "&aid=(?P<aid>[\\d\\.]+)&pid=(?P<ac>\\d+)&", "/click-(?P<ac>\\d+)-(?P<aid>[\\d\\.]+)", "shareasale\\.com[^?]*\\?(?P<query>.*)", "/t/\\d+-\\d+-(?P<ac>\\d+)-\\d+", "linkconnector\\.com[^?]*\\?(?P<query>.*)", "(?:/BI/(?P<ac>\\d+)/KBID/(?P<aid>\\d+))|(?:BI=(?P<ac>\\d+).+?KBID=(?P<aid>\\d+))"],
//        "deleted": false,
//        "locked": false,
//        "showQualityButton": "false",
//        "fbConversionPixel": "",
//        "bottomLogoUrl": "//assets.viewbix.com/eaac4baf-2971-40d5-9b12-76e79202bf40.png",
//        "defaultTwitterMessage": "Check out this video for {title}: {link}",
//        "titleTextFormatColor": "0xFFFFFF",
//        "facebookSharePageUrl": "",
//        "preRollApps": "[]",
//        "useYouTubeHighQuality": "false",
//        "playVideoInApps": "false",
//        "showTwitterButton": "true",
//        "customCss": "",
//        "videoEmailUrl": "",
//        "bannerApps": "",
//        "tinyUrl": "http://tinyurl.com/hytmbhk",
//        "showShareButton": "true",
//        "bottomLogoLink": "http://www.nguyenkim.com/su-kien-khuyen-mai.html",
//        "videoThumbnailUrl": "//assets.viewbix.com/4dc78442-b3ce-446a-aaf7-92c3c452b4b2.jpg",
//        "captions": "",
//        "showFacebookButton": "true",
//        "keepControlsVisible": "false",
//        "ctaButtonBackgroundColor": "16763904",
//        "customLogoUrl": "//assets.viewbix.com/b487cac8-87b9-43fc-8182-15ff03e9e54b.png",
//        "ctaApps": "",
//        "customLogoLink": "http://www.nguyenkim.com/",
//        "showHideUi": "",
//        "ctaLink": "http://www.nguyenkim.com/dien-thoai-samsung-galaxy-s6-edge-sm-g925-den.html",
//        "title": "Samsung Galaxy S6 edge+ : Official Introduction",
//        "ctaText": "Mua Ngay",
//        "videoLink": "https://www.thegioididong.com/dtdd/samsung-galaxy-s6-edge",
//        "videoUrl": "http://demo.easyvideo.vn/samsung_s6e.mp4",
//        "midRollApps": "[{\"startTime\":\"30\",\"playerAppInternalId\":\"eb1b93e9-1563-46cb-8704-727c8820fd39\"}]",
//        "ctaButtonButtonTextFormatColor": "0x000000",
//        "postRollApps": "[{\"playerAppInternalId\":\"3656706f-09a0-4738-8a60-ea86295bbc60\"}]",
//        "standardTextFormatFont": "Arial",
//        "scaleLogoToTitleBar": "true",
//        "openvvTrackScriptUrl": "",
//        "applications": [{
//            "id": "5b279456-05bd-40cd-9963-758c5aad8989",
//            "internalId": "dfc72dfb-6f3d-4945-b7ef-e54a82d856be",
//            "component": "com.qoof.sdk.components.rss.RSSItem",
//            "order": 0,
//            "mid_roll_app.startTime": "29",
//            "thumbnailWidth": "190",
//            "feedXmlString": "<feed><entry><id></id><title>ĐIỆN THOẠI SAMSUNG GALAXY S6 EDGE 32GB</title><content>Màn hình:\tSuper AMOLED, 5.1&quot;, Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 &amp; 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</content><thumbnailUrl></thumbnailUrl><link></link><contentSnippet>Màn hình:\tSuper AMOLED, 5.1&quot;, Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 &amp; 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</contentSnippet><publishedDate></publishedDate><index></index></entry></feed>",
//            "showInMenu": "true",
//            "icon": "/storage/content/icon/16/details.png",
//            "label": "Thông tin sản phẩm"
//        }, {
//            "id": "9cbcb03e-3fa9-4d38-9ca4-8a4984714ea9",
//            "internalId": "eb1b93e9-1563-46cb-8704-727c8820fd39",
//            "component": "com.qoof.sdk.components.link.CustomEmbed",
//            "order": 1,
//            "showInMenu": "true",
//            "icon": "/storage/content/icon/16/shopcart.png",
//            "text1": "http://www.nguyenkim.com/dien-thoai-samsung-galaxy-s6-edge-sm-g925-den.html",
//            "mid_roll_app.startTime": "30",
//            "label": "Mua ngay"
//        }, {
//            "id": "5508742d-a8b8-4dd2-8721-aa97b0d22bcb",
//            "internalId": "3656706f-09a0-4738-8a60-ea86295bbc60",
//            "component": "com.qoof.sdk.components.qr.QRCode",
//            "order": 2,
//            "icon": "/storage/content/icon/16/qr.png",
//            "showInMenu": "true",
//            "instructions": "Scan barcode và nhắn tin về tổng đài 999 để nhận để nhận mã giảm giá VIP",
//            "message": "NGUYENKIM_S6_DIS30PER",
//            "label": "Đăng ký - Giảm ngay 1 triệu",
//            "mid_roll_app.startTime": "30"
//        }, {
//            "id": "7f44155e-ba7d-4777-bc87-f3b7ac155791",
//            "internalId": "7360f22f-1793-4ce4-aea8-4da82b65c364",
//            "component": "com.qoof.sdk.components.contact.Skype",
//            "order": 3,
//            "showInMenu": "true",
//            "address": "duyliem2012",
//            "icon": "/storage/content/icon/16/skype.png",
//            "label": "Hỗ trợ tư vấn",
//            "instructions": "Hãy liên hệ chúng tôi để được tư vấn tốt nhất"
//        }, {
//            "id": "2ee839af-3090-428a-9594-dfa3a214c2f7",
//            "internalId": "2f834144-1334-440c-97ca-a9b1d96b06f6",
//            "component": "com.qoof.sdk.components.map.GoogleMap",
//            "order": 4,
//            "address": "63 Trần Hưng Đạo, P. Cầu Ông Lãnh, Q.1, TP Hồ Chí Minh",
//            "label": "Cửa hàng trưng bày",
//            "zoom": "15",
//            "showInMenu": "true",
//            "icon": "/storage/content/icon/16/google_map.png",
//            "title": "Trải nghiệm sản phẩm tại TTMS Nguyễn Kim"
//        }, {
//            "id": "bf5ff2c0-905d-45d0-851f-096ccbd62227",
//            "internalId": "8f6f61d1-a0f1-443f-a3e7-5720be87bd20",
//            "component": "com.qoof.sdk.components.forms.MailForm",
//            "order": 5,
//            "includeComments": "true",
//            "from": "campaign_s6e@nguyenkim.com",
//            "emails": "liempnd@saobacdau.vn",
//            "commentsLabel": "Thông tin góp ý",
//            "checkboxLabel": "Gửi phản hồi cho tôi",
//            "submitText": "Gửi",
//            "includeCheckbox": "true",
//            "success": "Cám ơn bạn đã gửi thông tin",
//            "icon": "/storage/content/icon/16/mail.png",
//            "label": "Góp ý sản phẩm",
//            "showInMenu": "true",
//            "instructions": "Vui lòng điền thông tin và nhấn nút \"Gửi\""
//        }],
//        "playerId": "86bdea80-2497-4afb-9017-e9da70859c01",
//        "memberId": "ffb8a5fd-6ea7-4ce6-bcc1-9c2b2254898d"
//    };
//}
function getPlayerConfigurations() {
    return {
        //"affiliateRegex": ["greensmoke\\.co.+?\\/aff\\/(?P<ac>\\d+)\\/ad\\/(?P<aid>\\d+)", "tplclick\\?lid=\\d+&pubid=(?P<ac>.+)", "bin/.+?\\?id=(?P<ac>[^&]+)&offerid=(?P<aid>[^&]+)|bin/.+?\\?id=(?P<ac>.+?)&", "&pubid=(?P<ac>[^&]*)", "&aid=(?P<aid>[\\d\\.]+)&pid=(?P<ac>\\d+)&", "/click-(?P<ac>\\d+)-(?P<aid>[\\d\\.]+)", "shareasale\\.com[^?]*\\?(?P<query>.*)", "/t/\\d+-\\d+-(?P<ac>\\d+)-\\d+", "linkconnector\\.com[^?]*\\?(?P<query>.*)", "(?:/BI/(?P<ac>\\d+)/KBID/(?P<aid>\\d+))|(?:BI=(?P<ac>\\d+).+?KBID=(?P<aid>\\d+))"],
        "deleted": false,
        "locked": false,
        "ctaLink": "http://saobacdau.vn",
        "videoEmailUrl": "",
        "ctaApps": "",
        "ctaButtonBackgroundColor": "16763904",
        "customLogoLink": "http://saobacdau.vn",
        "showQualityButton": "false",
        "showTwitterButton": "true",
        "bannerApps": "",
        "customLogoUrl": "/storage/content/img/sbd_logo.png",
        "showShareButton": "true",
        "showFacebookButton": "true",
        "midRollApps": "[[[= model.midRollApps || '']]]",
        //"midRollApps": "[{\"startTime\":\"29\",\"playerAppInternalId\":\"dfc72dfb-6f3d-4945-b7ef-e54a82d856be\"}]",
        "bottomLogoUrl": "",
        "ctaText": "Liên Hệ",
        //"preRollApps": "",
        "preRollApps": "[[[= model.preRollApps || '']]]",
        "facebookSharePageUrl": "",
        //"tinyUrl": "http://tinyurl.com/hh6j6t7",
        "tinyUrl": "",
        "titleTextFormatColor": "0xFFFFFF",
        "defaultTwitterMessage": "Check out this video for {title}: {link}",
        "bottomLogoLink": "",
        "fbConversionPixel": "",
        "keepControlsVisible": "false",
        "videoThumbnailUrl": "[[[= model.thumbnail]]]",
        "showHideUi": "",
        //"postRollApps": "",
        "postRollApps": "[[[= model.postRollApps || '']]]",
        "showViewbixBranding": "false",
        "standardTextFormatFont": "Arial",
        "videoLink": "",
        "useYouTubeHighQuality": "false",
        "videoUrl": "[[[= model.url]]]",
        //"detailsAppId": "7b5bea38-76df-4e26-8462-22356a28eafd",
        "detailsAppId": "",
        "openvvTrackScriptUrl": "",
        "ctaButtonButtonTextFormatColor": "0x000000",
        "title": "[[[= model.name]]]",
        "scaleLogoToTitleBar": "true",
        "playVideoInApps": "false",
        "applications": [[[= JSON.stringify(model.applications)]]],
        //"applications": [{
        //    "_id": "56cec64af8530803749b78ec",
        //    "categories": "commerce",
        //    "type": "rssfeed",
        //    "component": "com.qoof.sdk.components.rss.RSSItem",
        //    "label": "Thông tin",
        //    "title": "ĐIỆN THOẠI SAMSUNG GALAXY S6 EDGE 32GB",
        //    "thumbnailUrl": "http://st.gao.easyvideo.vn/thumb/So/zuY/KjEGrnfY8k4Y/SozuYKjEGrnfY8k4Y.jpg",
        //    "thumbnailWidth": "80",
        //    "content": "Màn hình:\tSuper AMOLED, 5.1\", Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 & 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh",
        //    "menu": "1",
        //    "ownerId": "mRyrgujASHyfRHrLB",
        //    "feedXmlString": "<feed><entry><id></id><title>ĐIỆN THOẠI SAMSUNG GALAXY S6 EDGE 32GB</title><content>Màn hình:\tSuper AMOLED, 5.1\", Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 & 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</content><thumbnailUrl>http://st.gao.easyvideo.vn/thumb/So/zuY/KjEGrnfY8k4Y/SozuYKjEGrnfY8k4Y.jpg</thumbnailUrl><link></link><contentSnippet>Màn hình:\tSuper AMOLED, 5.1\", Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 & 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</contentSnippet><publishedDate></publishedDate><index></index></entry></feed>",
        //    "icon": "http://dp.gao.easyvideo.vn/storage/content/icon/svg/details.svg",
        //    "id": "56cec64af8530803749b78ec",
        //    "internalId": "56cec64af8530803749b78ec"
        //}],
        //"applications": [
        //    {
        //        "id": "5b279456-05bd-40cd-9963-758c5aad8989",
        //        "internalId": "dfc72dfb-6f3d-4945-b7ef-e54a82d856be",
        //        "component": "com.qoof.sdk.components.rss.RSSItem",
        //        "order": 0,
        //        "mid_roll_app.startTime": "29",
        //        "thumbnailWidth": "190",
        //        //"feedXmlString": "<feed><entry><id></id><title>ĐIỆN THOẠI SAMSUNG GALAXY S6 EDGE 32GB</title><content>Màn hình:\tSuper AMOLED, 5.1&quot;, Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 &amp; 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</content><thumbnailUrl></thumbnailUrl><link></link><contentSnippet>Màn hình:\tSuper AMOLED, 5.1&quot;, Quad HD\nHệ điều hành:\tAndroid 5.0 (Lollipop)\nCamera sau:\t16 MP\nCamera trước:\t5 MP\nCPU:\tExynos 7420 8 nhân 64-bit, 4 nhân 1.5 GHz Cortex-A53 &amp; 4 nhân 2.1 GHz Cortex-A57\nRAM:\t3 GB\nBộ nhớ trong:\t32 GB\nHỗ trợ thẻ nhớ:\tKhông, Không\nThẻ SIM:\t1 Sim, Nano SIM\nKết nối:\tWiFi, 3G, 4G LTE Cat 6\nDung lượng pin:\t2600 mAh\nThiết kế:\tPin liền\nChức năng đặc biệt:\tMở khóa bằng vân tay, Sạc pin không dây, Sạc pin nhanh</contentSnippet><publishedDate></publishedDate><index></index></entry></feed>",
        //        "showInMenu": "true",
        //        "icon": "/storage/content/icon/16/details.png",
        //        "label": "Thông tin sản phẩm"
        //    }],
            //{
            //    "id": "bbca8e02-ef88-40a5-8680-c016181ba6eb",
            //    "internalId": "b7781904-f679-47b4-89be-497819160d1f",
            //    "component": "com.qoof.sdk.components.link.NavLink",
            //    "order": 22,
            //    "icon": "/storage/content/icon/16/hand.png",
            //    "label": "Open URL",
            //    "url": "http://asdfasd",
            //    "showInMenu": "true",
            //    "navLink": "true"
            //},
            //{
            //    "id": "7b5bea38-76df-4e26-8462-22356a28eafd",
            //    "internalId": "2775c698-6307-4565-9446-dbdf3037c616",
            //    "component": "com.qoof.sdk.components.rss.RSSItem",
            //    "order": 1,
            //    "thumbnailWidth": "70",
            //    "label": "About",
            //    "showInMenu": "true",
            //    "feedXmlString": "<feed><entry><id></id><title>Quảng Cáo Vinamilk Trung Thu Vui nhộn dành cho bé 2015</title><content>Nguồn :https://www.youtube.com/watch?v=rWg4fhE0XA0\nhttps://www.youtube.com/watch?v=Ov_tzqOIy10\nhttps://www.youtube.com/watch?v=3Wr2JqayI3w\nhttps://www.youtube.com/watch?v=7t2TCZIjIDg\nhttps://www.youtube.com/watch?v=fJfRHkE9G-I</content><thumbnailUrl></thumbnailUrl><link></link><contentSnippet>Nguồn :https://www.youtube.com/watch?v=rWg4fhE0XA0\nhttps://www.youtube.com/watch?v=Ov_tzqOIy10\nhttps://www.youtube.com/watch?v=3Wr2JqayI3w\nhttps://www.youtube.com/watch?v=7t2TCZIjIDg\nhttps://www.youtube.com/watch?v=fJfRHkE9G-I</contentSnippet><publishedDate></publishedDate><index>1</index><autoGen>true</autoGen></entry></feed>",
            //    "icon": "/storage/content/icon/16/details.png"
            //}, {
            //    "id": "f726ccd7-0dd8-4160-a86f-5b966b9dd0de",
            //    "internalId": "cd6315ae-5cd2-41cf-8dd9-a4024ac290ab",
            //    "component": "com.qoof.sdk.components.forms.MailForm",
            //    "order": 2,
            //    "instructions": "Please fill in the form below and click \"Submit\".",
            //    "includeComments": "false",
            //    "checkboxLabel": "Add me to list",
            //    "icon": "/storage/content/icon/16/mail.png",
            //    "from": "viewbix-lead@viewbix.com",
            //    "label": "Mail Form",
            //    "emails": "vutt@saobacdau.vn",
            //    "commentsLabel": "Comments",
            //    "showInMenu": "true",
            //    "success": "Thank you for contacting us.",
            //    "submitText": "Submit",
            //    "includeCheckbox": "false"
            //}
        //],
        //"playerId": "baeb23a9-e9f0-420a-ac33-c1074a8e5be3",
        "playerId": "",
        //"memberId": "ffb8a5fd-6ea7-4ce6-bcc1-9c2b2254898d"
        "memberId": ""
    };
}
