"object"!==typeof JSON2&&"object"===typeof window.JSON&&window.JSON.stringify&&window.JSON.parse?JSON2=window.JSON:function(){var t={};(function(){function g(m,t){function x(a){if(x[a]!==B)return x[a];var c;if("bug-string-char-index"==a)c=!1;else if("json"==a)c=x("json-stringify")&&x("json-parse");else{var b;if("json-stringify"==a){c=t.stringify;var Ba="function"==typeof c&&D;if(Ba){(b=function(){return 1}).toJSON=b;try{Ba="0"===c(0)&&"0"===c(new F)&&'""'==c(new E)&&c(C)===B&&c(B)===B&&c()===B&&"1"===
c(b)&&"[1]"==c([b])&&"[null]"==c([B])&&"null"==c(null)&&"[null,null,null]"==c([B,C,null])&&'{"a":[1,true,false,null,"\\u0000\\b\\n\\f\\r\\t"]}'==c({a:[b,!0,!1,null,"\x00\b\n\f\r\t"]})&&"1"===c(null,b)&&"[\n 1,\n 2\n]"==c([1,2],null,1)&&'"-271821-04-20T00:00:00.000Z"'==c(new P(-864E13))&&'"+275760-09-13T00:00:00.000Z"'==c(new P(864E13))&&'"-000001-01-01T00:00:00.000Z"'==c(new P(-621987552E5))&&'"1969-12-31T23:59:59.999Z"'==c(new P(-1))}catch(f){Ba=!1}}c=Ba}if("json-parse"==a){c=t.parse;if("function"==
typeof c)try{if(0===c("0")&&!c(!1)){b=c('{"a":[1,true,false,null,"\\u0000\\b\\n\\f\\r\\t"]}');var v=5==b.a.length&&1===b.a[0];if(v){try{v=!c('"\t"')}catch(f){}if(v)try{v=1!==c("01")}catch(f){}if(v)try{v=1!==c("1.")}catch(f){}}}}catch(f){v=!1}c=v}}return x[a]=!!c}m||(m=w.Object());t||(t=w.Object());var F=m.Number||w.Number,E=m.String||w.String,Q=m.Object||w.Object,P=m.Date||w.Date,W=m.SyntaxError||w.SyntaxError,ea=m.TypeError||w.TypeError,K=m.Math||w.Math,aa=m.JSON||w.JSON;"object"==typeof aa&&aa&&
(t.stringify=aa.stringify,t.parse=aa.parse);var Q=Q.prototype,C=Q.toString,H,fa,B,D=new P(-0xc782b5b800cec);try{D=-109252==D.getUTCFullYear()&&0===D.getUTCMonth()&&1===D.getUTCDate()&&10==D.getUTCHours()&&37==D.getUTCMinutes()&&6==D.getUTCSeconds()&&708==D.getUTCMilliseconds()}catch(d){}if(!x("json")){var S=x("bug-string-char-index");if(!D)var r=K.floor,I=[0,31,59,90,120,151,181,212,243,273,304,334],ga=function(a,b){return I[b]+365*(a-1970)+r((a-1969+(b=+(1<b)))/4)-r((a-1901+b)/100)+r((a-1601+b)/
400)};(H=Q.hasOwnProperty)||(H=function(a){var b={},e;(b.__proto__=null,b.__proto__={toString:1},b).toString!=C?H=function(a){var b=this.__proto__;a=a in(this.__proto__=null,this);this.__proto__=b;return a}:(e=b.constructor,H=function(a){var b=(this.constructor||e).prototype;return a in this&&!(a in b&&this[a]===b[a])});b=null;return H.call(this,a)});fa=function(a,b){var e=0,f,v,k;(f=function(){this.valueOf=0}).prototype.valueOf=0;v=new f;for(k in v)H.call(v,k)&&e++;f=v=null;e?fa=2==e?function(a,
b){var d={},c="[object Function]"==C.call(a),e;for(e in a)c&&"prototype"==e||H.call(d,e)||!(d[e]=1)||!H.call(a,e)||b(e)}:function(a,b){var d="[object Function]"==C.call(a),c,e;for(c in a)d&&"prototype"==c||!H.call(a,c)||(e="constructor"===c)||b(c);(e||H.call(a,c="constructor"))&&b(c)}:(v="valueOf toString toLocaleString propertyIsEnumerable isPrototypeOf hasOwnProperty constructor".split(" "),fa=function(a,b){var d="[object Function]"==C.call(a),c,e=!d&&"function"!=typeof a.constructor&&N[typeof a.hasOwnProperty]&&
a.hasOwnProperty||H;for(c in a)d&&"prototype"==c||!e.call(a,c)||b(c);for(d=v.length;c=v[--d];e.call(a,c)&&b(c));});return fa(a,b)};if(!x("json-stringify")){var h={92:"\\\\",34:'\\"',8:"\\b",12:"\\f",10:"\\n",13:"\\r",9:"\\t"},G=function(a,b){return("000000"+(b||0)).slice(-a)},ha=function(a){for(var b='"',e=0,f=a.length,v=!S||10<f,k=v&&(S?a.split(""):a);e<f;e++){var l=a.charCodeAt(e);switch(l){case 8:case 9:case 10:case 12:case 13:case 34:case 92:b+=h[l];break;default:b=32>l?b+("\\u00"+G(2,l.toString(16))):
b+(v?k[e]:a.charAt(e))}}return b+'"'},ma=function(a,b,e,f,v,k,l){var u,g,q,h,p,m,w,y,t;try{u=b[a]}catch(x){}if("object"==typeof u&&u)if(g=C.call(u),"[object Date]"!=g||H.call(u,"toJSON"))"function"==typeof u.toJSON&&("[object Number]"!=g&&"[object String]"!=g&&"[object Array]"!=g||H.call(u,"toJSON"))&&(u=u.toJSON(a));else if(u>-1/0&&u<1/0){if(ga){h=r(u/864E5);for(g=r(h/365.2425)+1970-1;ga(g+1,0)<=h;g++);for(q=r((h-ga(g,0))/30.42);ga(g,q+1)<=h;q++);h=1+h-ga(g,q);p=(u%864E5+864E5)%864E5;m=r(p/36E5)%
24;w=r(p/6E4)%60;y=r(p/1E3)%60;p%=1E3}else g=u.getUTCFullYear(),q=u.getUTCMonth(),h=u.getUTCDate(),m=u.getUTCHours(),w=u.getUTCMinutes(),y=u.getUTCSeconds(),p=u.getUTCMilliseconds();u=(0>=g||1E4<=g?(0>g?"-":"+")+G(6,0>g?-g:g):G(4,g))+"-"+G(2,q+1)+"-"+G(2,h)+"T"+G(2,m)+":"+G(2,w)+":"+G(2,y)+"."+G(3,p)+"Z"}else u=null;e&&(u=e.call(b,a,u));if(null===u)return"null";g=C.call(u);if("[object Boolean]"==g)return""+u;if("[object Number]"==g)return u>-1/0&&u<1/0?""+u:"null";if("[object String]"==g)return ha(""+
u);if("object"==typeof u){for(a=l.length;a--;)if(l[a]===u)throw ea();l.push(u);t=[];b=k;k+=v;if("[object Array]"==g){q=0;for(a=u.length;q<a;q++)g=ma(q,u,e,f,v,k,l),t.push(g===B?"null":g);a=t.length?v?"[\n"+k+t.join(",\n"+k)+"\n"+b+"]":"["+t.join(",")+"]":"[]"}else fa(f||u,function(a){var b=ma(a,u,e,f,v,k,l);b!==B&&t.push(ha(a)+":"+(v?" ":"")+b)}),a=t.length?v?"{\n"+k+t.join(",\n"+k)+"\n"+b+"}":"{"+t.join(",")+"}":"{}";l.pop();return a}};t.stringify=function(a,b,e){var g,f,k,l;if(N[typeof b]&&b)if("[object Function]"==
(l=C.call(b)))f=b;else if("[object Array]"==l){k={};for(var h=0,r=b.length,q;h<r;q=b[h++],(l=C.call(q),"[object String]"==l||"[object Number]"==l)&&(k[q]=1));}if(e)if("[object Number]"==(l=C.call(e))){if(0<(e-=e%1))for(g="",10<e&&(e=10);g.length<e;g+=" ");}else"[object String]"==l&&(g=10>=e.length?e:e.slice(0,10));return ma("",(q={},q[""]=a,q),f,k,g,"",[])}}if(!x("json-parse")){var y=E.fromCharCode,wa={92:"\\",34:'"',47:"/",98:"\b",116:"\t",110:"\n",102:"\f",114:"\r"},k,U,A=function(){k=U=null;throw W();
},f=function(){for(var a=U,b=a.length,e,g,f,h,l;k<b;)switch(l=a.charCodeAt(k),l){case 9:case 10:case 13:case 32:k++;break;case 123:case 125:case 91:case 93:case 58:case 44:return e=S?a.charAt(k):a[k],k++,e;case 34:e="@";for(k++;k<b;)if(l=a.charCodeAt(k),32>l)A();else if(92==l)switch(l=a.charCodeAt(++k),l){case 92:case 34:case 47:case 98:case 116:case 110:case 102:case 114:e+=wa[l];k++;break;case 117:g=++k;for(f=k+4;k<f;k++)l=a.charCodeAt(k),48<=l&&57>=l||97<=l&&102>=l||65<=l&&70>=l||A();e+=y("0x"+
a.slice(g,k));break;default:A()}else{if(34==l)break;l=a.charCodeAt(k);for(g=k;32<=l&&92!=l&&34!=l;)l=a.charCodeAt(++k);e+=a.slice(g,k)}if(34==a.charCodeAt(k))return k++,e;A();default:g=k;45==l&&(h=!0,l=a.charCodeAt(++k));if(48<=l&&57>=l){for(48==l&&(l=a.charCodeAt(k+1),48<=l&&57>=l)&&A();k<b&&(l=a.charCodeAt(k),48<=l&&57>=l);k++);if(46==a.charCodeAt(k)){for(f=++k;f<b&&(l=a.charCodeAt(f),48<=l&&57>=l);f++);f==k&&A();k=f}l=a.charCodeAt(k);if(101==l||69==l){l=a.charCodeAt(++k);43!=l&&45!=l||k++;for(f=
k;f<b&&(l=a.charCodeAt(f),48<=l&&57>=l);f++);f==k&&A();k=f}return+a.slice(g,k)}h&&A();if("true"==a.slice(k,k+4))return k+=4,!0;if("false"==a.slice(k,k+5))return k+=5,!1;if("null"==a.slice(k,k+4))return k+=4,null;A()}return"$"},p=function(a){var b,e;"$"==a&&A();if("string"==typeof a){if("@"==(S?a.charAt(0):a[0]))return a.slice(1);if("["==a){for(b=[];;e||(e=!0)){a=f();if("]"==a)break;e&&(","==a?(a=f(),"]"==a&&A()):A());","==a&&A();b.push(p(a))}return b}if("{"==a){for(b={};;e||(e=!0)){a=f();if("}"==
a)break;e&&(","==a?(a=f(),"}"==a&&A()):A());","!=a&&"string"==typeof a&&"@"==(S?a.charAt(0):a[0])&&":"==f()||A();b[a.slice(1)]=p(f())}return b}A()}return a},a=function(a,c,e){e=b(a,c,e);e===B?delete a[c]:a[c]=e},b=function(b,c,e){var f=b[c],g;if("object"==typeof f&&f)if("[object Array]"==C.call(f))for(g=f.length;g--;)a(f,g,e);else fa(f,function(b){a(f,b,e)});return e.call(b,c,f)};t.parse=function(a,c){var e,g;k=0;U=""+a;e=p(f());"$"!=f()&&A();k=U=null;return c&&"[object Function]"==C.call(c)?b((g=
{},g[""]=e,g),"",c):e}}}t.runInContext=g;return t}var W="function"===typeof define&&define.amd,N={"function":!0,object:!0},m=N[typeof t]&&t&&!t.nodeType&&t,w=N[typeof window]&&window||this,x=m&&N[typeof module]&&module&&!module.nodeType&&"object"==typeof global&&global;!x||x.global!==x&&x.window!==x&&x.self!==x||(w=x);if(m&&!W)g(w,m);else{var F=w.JSON,Q=w.JSON3,E=!1,K=g(w,w.JSON3={noConflict:function(){E||(E=!0,w.JSON=F,w.JSON3=Q,F=Q=null);return K}});w.JSON={parse:K.parse,stringify:K.stringify}}W&&
define(function(){return K})}).call(this);JSON2=t}();"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof GaoTracker&&(GaoTracker=function(){function t(a){try{return wa(a)}catch(b){return unescape(a)}}function g(a){return"undefined"!==typeof a}function W(a){return"function"===typeof a}function N(a){return"object"===typeof a}function m(a){return"string"===typeof a||a instanceof String}function w(a){if(!a)return!0;var b,d=!0;for(b in a)Object.prototype.hasOwnProperty.call(a,b)&&(d=!1);return d}function x(){var a,b,d;for(a=0;a<arguments.length;a+=1)d=arguments[a],b=d.shift(),m(b)?k[b].apply(k,
d):b.apply(k,d)}function F(a,b,d,c){if(a.addEventListener)return a.addEventListener(b,d,c),!0;if(a.attachEvent)return a.attachEvent("on"+b,d);a["on"+b]=d}function Q(a,b){var d="",c,e;for(c in S)Object.prototype.hasOwnProperty.call(S,c)&&(e=S[c][a],W(e)&&(d+=e(b)));return d}function E(){var a;if(!ha)for(ha=!0,Q("load"),a=0;a<ma.length;a++)ma[a]();return!0}function K(a,b){var d=r.createElement("script");d.type="text/javascript";d.src=a;d.readyState?d.onreadystatechange=function(){var a=this.readyState;
if("loaded"===a||"complete"===a)d.onreadystatechange=null,b()}:d.onload=b;r.getElementsByTagName("head")[0].appendChild(d)}function bc(){var a="";try{a=h.top.document.referrer}catch(b){if(h.parent)try{a=h.parent.document.referrer}catch(d){a=""}}""===a&&(a=r.referrer);return a}function qb(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function ra(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function Ta(a,b){var d=(new RegExp("[\\?&#]"+b+"=([^&#]*)")).exec(a);return d?
wa(d[1]):""}function cc(a){var b=function(a,b){return a<<b|a>>>32-b},d=function(a){var b="",c,d;for(c=7;0<=c;c--)d=a>>>4*c&15,b+=d.toString(16);return b},c,e,f=[],g=1732584193,k=4023233417,l=2562383102,h=271733878,r=3285377520,q,p,m,t,w,x=[];a=unescape(y(a));q=a.length;for(c=0;c<q-3;c+=4)e=a.charCodeAt(c)<<24|a.charCodeAt(c+1)<<16|a.charCodeAt(c+2)<<8|a.charCodeAt(c+3),x.push(e);switch(q&3){case 0:c=2147483648;break;case 1:c=a.charCodeAt(q-1)<<24|8388608;break;case 2:c=a.charCodeAt(q-2)<<24|a.charCodeAt(q-
1)<<16|32768;break;case 3:c=a.charCodeAt(q-3)<<24|a.charCodeAt(q-2)<<16|a.charCodeAt(q-1)<<8|128}for(x.push(c);14!==(x.length&15);)x.push(0);x.push(q>>>29);x.push(q<<3&4294967295);for(a=0;a<x.length;a+=16){for(c=0;16>c;c++)f[c]=x[a+c];for(c=16;79>=c;c++)f[c]=b(f[c-3]^f[c-8]^f[c-14]^f[c-16],1);e=g;q=k;p=l;m=h;t=r;for(c=0;19>=c;c++)w=b(e,5)+(q&p|~q&m)+t+f[c]+1518500249&4294967295,t=m,m=p,p=b(q,30),q=e,e=w;for(c=20;39>=c;c++)w=b(e,5)+(q^p^m)+t+f[c]+1859775393&4294967295,t=m,m=p,p=b(q,30),q=e,e=w;for(c=
40;59>=c;c++)w=b(e,5)+(q&p|q&m|p&m)+t+f[c]+2400959708&4294967295,t=m,m=p,p=b(q,30),q=e,e=w;for(c=60;79>=c;c++)w=b(e,5)+(q^p^m)+t+f[c]+3395469782&4294967295,t=m,m=p,p=b(q,30),q=e,e=w;g=g+e&4294967295;k=k+q&4294967295;l=l+p&4294967295;h=h+m&4294967295;r=r+t&4294967295}w=d(g)+d(k)+d(l)+d(h)+d(r);return w.toLowerCase()}function dc(a,b,d){a||(a="");b||(b="");if("translate.googleusercontent.com"===a)""===d&&(d=b),b=Ta(b,"u"),a=ra(b);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===
a.slice(0,5))b=r.links[0].href,a=ra(b);return[a,b,d]}function P(a){var b=a.length;"."===a.charAt(--b)&&(a=a.slice(0,b));"*."===a.slice(0,2)&&(a=a.slice(1));-1!==a.indexOf("/")&&(a=a.substr(0,a.indexOf("/")));return a}function va(a){return a?!g(a.children)&&g(a.childNodes)||g(a.children)?a.children:[]:[]}function ea(a,b){if(a&&a.indexOf)return a.indexOf(b);if(!g(a)||null===a||!a.length)return-1;var d=a.length;if(0===d)return-1;for(var c=0;c<d;){if(a[c]===b)return c;c++}return-1}function rb(a){function b(a,
b){if(h.getComputedStyle)return r.defaultView.getComputedStyle(a,null)[b];if(a.currentStyle)return a.currentStyle[b]}function d(c,e,f,k,h,l,p){var m=c.parentNode,q;a:{for(q=c.parentNode;q;){if(q===r){q=!0;break a}q=q.parentNode}q=!1}if(!q)return!1;if(9===m.nodeType)return!0;if("0"===b(c,"opacity")||"none"===b(c,"display")||"hidden"===b(c,"visibility"))return!1;g(e)&&g(f)&&g(k)&&g(h)&&g(l)&&g(p)||(e=c.offsetTop,h=c.offsetLeft,k=e+c.offsetHeight,f=h+c.offsetWidth,l=c.offsetWidth,p=c.offsetHeight);if(a===
c&&(0===p||0===l)&&"hidden"===b(c,"overflow"))return!1;if(m){if("hidden"===b(m,"overflow")||"scroll"===b(m,"overflow"))if(h+1>m.offsetWidth+m.scrollLeft||h+l-1<m.scrollLeft||e+1>m.offsetHeight+m.scrollTop||e+p-1<m.scrollTop)return!1;c.offsetParent===m&&(h+=m.offsetLeft,e+=m.offsetTop);return d(m,e,f,k,h,l,p)}return!0}return a?d(a):!1}function aa(a,b){if(b)return b;"piwik.php"===a.slice(-9)&&(a=a.slice(0,a.length-9));return a}function C(a){var b=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)(&segment=.*)?$/.exec(r.referrer);
if(b){if(b[1]!==String(a))return!1;a=b[2];var d=b[3];(b=b[4])?0===b.indexOf("&segment=")&&(b=b.substr(9)):b="";h.name="Piwik_Overlay###"+a+"###"+d+"###"+b}b=h.name.split("###");return 4===b.length&&"Piwik_Overlay"===b[0]}function H(a,b,d){var c=h.name.split("###"),e=c[1],f=c[2],g=c[3],k=aa(a,b);K(k+"plugins/Overlay/client/client.js?v=1",function(){Piwik_Overlay_Client.initialize(k,d,e,f,g)})}function fa(){if(g(h.frameElement))return h.frameElement&&"iframe"===String(h.frameElement.nodeName).toLowerCase();
try{return h.self!==h.top}catch(a){return!0}}function B(a,b){function d(a,n,b,c,d,e){if(!ia){var f;b&&(f=new Date,f.setTime(f.getTime()+b));r.cookie=a+"="+y(n)+(b?";expires="+f.toGMTString():"")+";path="+(c||"/")+(d?";domain="+d:"")+(e?";secure":"")}}function c(a){return ia?0:(a=(new RegExp("(^|;)[ ]*"+a+"=([^;]*)")).exec(r.cookie))?wa(a[2]):0}function e(a){var n;return ub?(n=/#.*/,a.replace(n,"")):a}function k(a,n){var b;a=String(a).toLowerCase();n=String(n).toLowerCase();if(a===n)return!0;if("."===
n.slice(0,1)){if(a===n.slice(1))return!0;b=a.length-n.length;if(0<b&&a.slice(b)===n)return!0}return!1}function v(a,n){a=String(a);return-1!==a.indexOf(n,a.length-n.length)}function x(a){var n=document.createElement("a");0!==a.indexOf("//")&&0!==a.indexOf("http")&&(a="http://"+a);n.href=p.toAbsoluteUrl(a);return n.pathname?n.pathname:""}function l(a,n){if(!n||"/"===n||a===n)return!0;if(!a)return!1;n=String(n).toLowerCase();a=String(a).toLowerCase();v(a,"/")||(a+="/");v(n,"/")||(n+="/");return 0===
a.indexOf(n)}function u(a,n){var b,c,d;for(b=0;b<R.length;b++)if(c=P(R[b]),d=x(R[b]),k(a,c)&&l(n,d))return!0;return!1}function A(a){var n,b,c;for(n=0;n<R.length;n++){b=P(R[n].toLowerCase());if(a===b)return!0;if("."===b.slice(0,1)){if(a===b.slice(1))return!0;c=a.length-b.length;if(0<c&&a.slice(c)===b)return!0}}return!1}function q(a,n){var b=new Image(1,1);b.onload=function(){U=0;"function"===typeof n&&n()};b.src=X+(0>X.indexOf("?")?"?":"&")+a}function B(a,n,b){g(b)&&null!==b||(b=!0);try{var c=h.XMLHttpRequest?
new h.XMLHttpRequest:h.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;c.open("POST",X,!0);c.onreadystatechange=function(){4!==this.readyState||200<=this.status&&300>this.status||!b?"function"===typeof n&&n():q(a,n)};c.setRequestHeader("Content-Type",vb);c.send(a)}catch(d){b&&q(a,n)}}function E(a){a=(new Date).getTime()+a;if(!D||a>D)D=a}function K(a){!ba&&ca&&(ba=setTimeout(function(){ba=null;Da||(Da=!r.hasFocus||r.hasFocus());if(!Da)K(ca);else if(!Ua()){var a=ca-((new Date).getTime()-Ea),
a=Math.min(ca,a);K(a)}},a||ca))}function aa(){Da=!0;Ua()||K()}function va(){ba&&(clearTimeout(ba),ba=null)}function sb(){!Va&&ca&&(Va=!0,F(h,"focus",aa),F(h,"blur",va),K())}function tb(a){var n=(new Date).getTime();Ea=n;na&&n<na?(n=na-n,setTimeout(a,n),E(n+50),na+=50):(!1===na&&(na=n+800),a())}function T(a,n,b){!Fa&&a&&tb(function(){"POST"===wb?B(a,b):q(a,b);E(n)});Va?K():sb()}function Ca(a,n){var b;b=Fa?!1:a&&a.length;if(b){var c='{"requests":["?'+a.join('","?')+'"]}';tb(function(){B(c,null,!1);
E(n)})}}function Y(a){return xb+a+"."+L+"."+yb}function zb(){if(ia)return"0";if(!g(I.cookieEnabled)){var a=Y("testcookie");d(a,"1");return"1"===c(a)?"1":"0"}return I.cookieEnabled?"1":"0"}function Wa(){yb=Xa((oa||Ga)+(da||"/")).slice(0,4)}function Ya(){var a=Y("cvar"),a=c(a);return a.length&&(a=JSON2.parse(a),N(a))?a:{}}function Ab(){var a=Math.round((new Date).getTime()/1E3),n=Y("id");return(n=c(n))?(a=n.split("."),a.unshift("0"),xa.length&&(a[1]=xa),a):a=["1",xa.length?xa:"0"===zb()?"":Xa((I.userAgent||
"")+(I.platform||"")+JSON2.stringify(Z)+(new Date).getTime()+Math.random()).slice(0,16),a,0,a,"",""]}function Ha(){var a=Ab(),n=a[0],b=a[1],c=a[2],d=a[3],e=a[4],f=a[5];g(a[6])||(a[6]="");return{newVisitor:n,uuid:b,createTs:c,visitCount:d,currentVisitTs:e,lastVisitTs:f,lastEcommerceOrderTs:a[6]}}function Bb(){var a=(new Date).getTime(),n=Ha().createTs;return 1E3*parseInt(n,10)+Za-a}function $a(a){if(L){var n=Math.round((new Date).getTime()/1E3);g(a)||(a=Ha());a=a.uuid+"."+a.createTs+"."+a.visitCount+
"."+n+"."+a.lastVisitTs+"."+a.lastEcommerceOrderTs;d(Y("id"),a,Bb(),da,oa)}}function sa(){var a=c(Y("ref"));if(a.length)try{if(a=JSON2.parse(a),N(a))return a}catch(n){}return["","",0,""]}function ab(){var a=ia;ia=!1;var n=["id","ses","cvar","ref"],b,e;for(b=0;b<n.length;b++)e=Y(n[b]),0!==c(e)&&d(e,"",-86400,da,oa);ia=a}function Cb(a){if(a&&N(a)){var n=[],b;for(b in a)Object.prototype.hasOwnProperty.call(a,b)&&n.push(b);b={};n.sort();var c=n.length,d;for(d=0;d<c;d++)b[n[d]]=a[n[d]];return b}}function V(a,
n,b,f){function k(a,n){var b=JSON2.stringify(a);return 2<b.length?"&"+n+"="+y(b):""}var h,l=new Date,m=Math.round(l.getTime()/1E3),p,q,t,u,x=M,v=Y("ses"),C=Y("ref"),F=Y("cvar");t=c(v);u=sa();var E=Ia||bb,z,B;ia&&ab();if(Fa)return"";v=Ha();g(f)||(f="");var D=r.characterSet||r.charset;D&&"utf-8"!==D.toLowerCase()||(D=null);z=u[0];B=u[1];p=u[2];q=u[3];if(!t){t=Ja/1E3;if(!v.lastVisitTs||m-v.lastVisitTs>t)v.visitCount++,v.lastVisitTs=v.currentVisitTs;if(!cb||!z.length){for(h in Ka)if(Object.prototype.hasOwnProperty.call(Ka,
h)&&(z=Ta(E,Ka[h]),z.length))break;for(h in La)if(Object.prototype.hasOwnProperty.call(La,h)&&(B=Ta(E,La[h]),B.length))break}t=ra(ya);u=q.length?ra(q):"";!t.length||A(t)||cb&&u.length&&!A(u)||(q=ya);if(q.length||z.length)p=m,u=[z,B,p,e(q.slice(0,1024))],d(C,JSON2.stringify(u),Db,da,oa)}a+="&idsite="+L+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+l.getHours()+"&m="+l.getMinutes()+"&s="+l.getSeconds()+"&url="+y(e(E))+(ya.length?"&urlref="+y(e(ya)):"")+(ta&&ta.length?"&uid="+y(ta):"")+"&_id="+
v.uuid+"&_idts="+v.createTs+"&_idvc="+v.visitCount+"&_idn="+v.newVisitor+(z.length?"&_rcn="+y(z):"")+(B.length?"&_rck="+y(B):"")+"&_refts="+p+"&_viewts="+v.lastVisitTs+(String(v.lastEcommerceOrderTs).length?"&_ects="+v.lastEcommerceOrderTs:"")+(String(q).length?"&_ref="+y(e(q.slice(0,1024))):"")+(D?"&cs="+y(D):"")+"&send_image=0";for(h in Z)Object.prototype.hasOwnProperty.call(Z,h)&&(a+="&"+h+"="+Z[h]);l=[];if(n)for(h in n)Object.prototype.hasOwnProperty.call(n,h)&&/^dimension\d+$/.test(h)&&(m=h.replace("dimension",
""),l.push(parseInt(m,10)),l.push(String(m)),a+="&"+h+"="+n[h],delete n[h]);n&&w(n)&&(n=null);for(h in pa)Object.prototype.hasOwnProperty.call(pa,h)&&-1===l.indexOf(h)&&(a+="&dimension"+h+"="+pa[h]);n?a+="&data="+y(JSON2.stringify(n)):ja&&(a+="&data="+y(JSON2.stringify(ja)));n=Cb(qa);l=Cb(db);a+=k(n,"cvar");a+=k(l,"e_cvar");if(M){a+=k(M,"_cvar");for(h in x)Object.prototype.hasOwnProperty.call(x,h)&&(""!==M[h][0]&&""!==M[h][1]||delete M[h]);Eb&&d(F,JSON2.stringify(M),Ja,da,oa)}Fb&&(eb?a+="&gt_ms="+
eb:G&&G.timing&&G.timing.requestStart&&G.timing.responseEnd&&(a+="&gt_ms="+(G.timing.responseEnd-G.timing.requestStart)));v.lastEcommerceOrderTs=g(f)&&String(f).length?f:v.lastEcommerceOrderTs;$a(v);d(Y("ses"),"*",Ja,da,oa);a+=Q(b);fb.length&&(a+="&"+fb);W(gb)&&(a=gb(a));return a}function Gb(a,n,b,c,d,e){var f="idgoal=0",h,k=new Date,l=[],m;String(a).length&&(f+="&ec_id="+y(a),h=Math.round(k.getTime()/1E3));f+="&revenue="+n;String(b).length&&(f+="&ec_st="+b);String(c).length&&(f+="&ec_tx="+c);String(d).length&&
(f+="&ec_sh="+d);String(e).length&&(f+="&ec_dt="+e);if(J){for(m in J)Object.prototype.hasOwnProperty.call(J,m)&&(g(J[m][1])||(J[m][1]=""),g(J[m][2])||(J[m][2]=""),g(J[m][3])&&0!==String(J[m][3]).length||(J[m][3]=0),g(J[m][4])&&0!==String(J[m][4]).length||(J[m][4]=1),l.push(J[m]));f+="&ec_items="+y(JSON2.stringify(l))}f=V(f,ja,"ecommerce",h);T(f,z)}function hb(a,b){var c,d="(^| )(piwik[_-]"+b;if(a)for(c=0;c<a.length;c++)d+="|"+a[c];return new RegExp(d+")( |$)")}function za(a){return X&&a&&0===String(a).indexOf(X)}
function ib(a){var b=a,c;for(c=b.parentNode;null!==c&&g(c)&&!f.isLinkElement(b);)b=c,c=b.parentNode;a=b;if(f.hasNodeAttribute(a,"href")&&g(a.href)&&(b=f.getAttributeValueFromNode(a,"href"),!za(b))){var d=a.pathname||x(a.href),b=a.hostname||ra(a.href),e=b.toLowerCase(),b=a.href.replace(b,e);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(b)){c=a.className;d=u(e,d);a=f.hasNodeAttribute(a,"download");if(za(b))c=0;else{var e=hb(Hb,"download"),h=hb(Ib,"link"),k=new RegExp("\\.("+
ka.join("|")+")([?&#]|$)","i");c=h.test(c)?"link":a||e.test(c)||k.test(b)?"download":d?0:"link"}if(c)return{type:c,href:b}}}}function Aa(a,b,c,d){if(a=p.buildInteractionRequestParams(a,b,c,d))return V(a,null,"contentInteraction")}function Jb(a,b,c,d,e){if(g(a)){if(za(a))return a;var f=p.toAbsoluteUrl(a),f="redirecturl="+y(f)+"&",f=f+Aa(b,c,d,e||a);a="&";0>X.indexOf("?")&&(a="?");return X+a+f}}function jb(a,b){if(!a||!b)return!1;var c=p.findTargetNode(a);if(p.shouldIgnoreInteraction(c))return!1;var c=
p.findTargetNodeNoDefault(a),d;if(d=c)d=!(c&&b&&(c.contains?c.contains(b):c===b||c.compareDocumentPosition&&c.compareDocumentPosition(b)&16));return d?!1:!0}function Kb(a,b,c){if(a){var d=p.findParentContentNode(a);if(d&&jb(d,a)&&(a=p.buildContentBlock(d)))return!a.target&&c&&(a.target=c),p.buildInteractionRequestParams(b,a.name,a.piece,a.target)}}function Lb(a){if(!la||!la.length)return!1;var b,c;for(b=0;b<la.length;b++)if((c=la[b])&&c.name===a.name&&c.piece===a.piece&&c.target===a.target)return!0;
return!1}function kb(a){if(!a)return!1;var b=p.findTargetNode(a);if(!b||p.shouldIgnoreInteraction(b))return!1;var c=ib(b);if(lb&&c&&c.type)return!1;if(f.isLinkElement(b)&&f.hasNodeAttributeWithValue(b,"href")){c=String(f.getAttributeValueFromNode(b,"href"));if(0===c.indexOf("#"))return!1;if(za(c))return!0;if(!p.isUrlToCurrentDomain(c))return!1;var d=p.buildContentBlock(a);if(!d)return;a=d.name;var e=d.piece,d=d.target;if(!f.hasNodeAttributeWithValue(b,p.CONTENT_TARGET_ATTR)||b.wasContentTargetAttrReplaced)b.wasContentTargetAttrReplaced=
!0,d=p.toAbsoluteUrl(c),f.setAnyAttribute(b,p.CONTENT_TARGET_ATTR,d);c=Jb(c,"click",a,e,d);p.setHrefAttribute(b,c);return!0}return!1}function Mb(a){return function(b){if(a){var c=p.findParentContentNode(a),d;b&&(d=b.target||b.srcElement);d||(d=a);if(jb(c,d)){E(z);f.isLinkElement(a)&&f.hasNodeAttributeWithValue(a,"href")&&f.hasNodeAttributeWithValue(a,p.CONTENT_TARGET_ATTR)&&(b=f.getAttributeValueFromNode(a,"href"),!za(b)&&a.wasContentTargetAttrReplaced&&f.setAnyAttribute(a,p.CONTENT_TARGET_ATTR,""));
b=ib(a);if(Ma&&b&&b.type)return b.type;if(kb(c))return"href";if(c=p.buildContentBlock(c))return c=Aa("click",c.name,c.piece,c.target),T(c,z),c}}}}function Nb(a){if(a&&a.length){var b,c;for(b=0;b<a.length;b++)(c=p.findTargetNode(a[b]))&&!c.contentInteractionTrackingSetupDone&&(c.contentInteractionTrackingSetupDone=!0,F(c,"click",Mb(c)))}}function Ob(a,b){if(!a||!a.length)return[];var c,d;for(c=0;c<a.length;c++)Lb(a[c])?(a.splice(c,1),c--):la.push(a[c]);if(!a||!a.length)return[];if(b&&b.length)for(c=
0;c<b.length;c++)kb(b[c]);Nb(b);var e=[];for(c=0;c<a.length;c++)d=V(p.buildImpressionRequestParams(a[c].name,a[c].piece,a[c].target),void 0,"contentImpressions"),e.push(d);return e}function Na(a){var b=p.collectContent(a);return Ob(b,a)}function mb(a){if(!a||!a.length)return[];var b;for(b=0;b<a.length;b++)p.isNodeVisible(a[b])||(a.splice(b,1),b--);return a&&a.length?Na(a):[]}function Pb(a,b,c){a=p.buildImpressionRequestParams(a,b,c);return V(a,null,"contentImpression")}function Qb(a,b){if(a){var c=
p.findParentContentNode(a);if(c=p.buildContentBlock(c))return b||(b="Unknown"),Aa(b,c.name,c.piece,c.target)}}function Rb(a,b,c,d,e){if(0===String(a).length||0===String(b).length)return!1;a="e_c="+y(a)+"&e_a="+y(b)+(g(c)?"&e_n="+y(c):"")+(g(d)?"&e_v="+y(d):"");e=V(a,e,"event");T(e,z)}function Sb(a,b,c,d,f){b=b+"="+y(e(a));(a=Kb(f,"click",a))&&(b+="&"+a);c=V(b,c,"link");T(c,d?0:z,d)}function Tb(a,b){return""!==a?a+b.charAt(0).toUpperCase()+b.slice(1):b}function O(a){var b,c,d=["","webkit","ms","moz"],
e;if(!Ub)for(c=0;c<d.length;c++)if(e=d[c],Object.prototype.hasOwnProperty.call(r,Tb(e,"hidden"))){"prerender"===r[Tb(e,"visibilityState")]&&(b=!0);break}b?F(r,e+"visibilitychange",function ec(){r.removeEventListener(e+"visibilitychange",ec,!1);a()}):a()}function Oa(a){"complete"===r.readyState?a():h.addEventListener?h.addEventListener("load",a):h.attachEvent&&h.attachEvent("onLoad",a)}function nb(a){var b=!1;(b=r.attachEvent?"complete"===r.readyState:"loading"!==r.readyState)?a():r.addEventListener?
r.addEventListener("DOMContentLoaded",a):r.attachEvent&&r.attachEvent("onreadystatechange",a)}function ob(a){var b=ib(a);b&&b.type&&(b.href=t(b.href),Sb(b.href,b.type,void 0,null,a))}function Pa(a){return function(b){b=b||h.event;var c;a:{c=b;var d=c.which,e=typeof c.button;d||"undefined"===e||(r.all&&!r.addEventListener?c.button&1?d=1:c.button&2?d=3:c.button&4&&(d=2):0===c.button||"0"===c.button?d=1:c.button&1?d=2:c.button&2&&(d=3));switch(d){case 1:c="left";break a;case 2:c="middle";break a;case 3:c=
"right";break a}c=void 0}d=b.target||b.srcElement;"click"===b.type?(b=!1,a&&"middle"===c&&(b=!0),d&&!b&&ob(d)):"mousedown"===b.type?"middle"===c&&d?(Qa=c,Ra=d):Qa=Ra=null:"mouseup"===b.type?(c===Qa&&d===Ra&&ob(d),Qa=Ra=null):"contextmenu"===b.type&&ob(d)}}function Vb(a,b){F(a,"click",Pa(b),!1);b&&(F(a,"mouseup",Pa(b),!1),F(a,"mousedown",Pa(b),!1),F(a,"contextmenu",Pa(b),!1))}function Wb(a){if(!Ma){Ma=!0;var b,c=hb(Xb,"ignore"),d=r.links;if(d)for(b=0;b<d.length;b++)c.test(d[b].className)||Vb(d[b],
a)}}function Yb(a,b,c){function d(){e=!0}if(ua)return!0;ua=!0;var e=!1,f,g;Oa(function(){function k(a){setTimeout(function(){ua&&(e=!1,c.trackVisibleContentImpressions(),k(a))},a)}function l(a){setTimeout(function(){ua&&(e&&(e=!1,c.trackVisibleContentImpressions()),l(a))},a)}if(a){f=["scroll","resize"];for(g=0;g<f.length;g++)r.addEventListener?r.addEventListener(f[g],d):h.attachEvent("on"+f[g],d);l(100)}b&&0<b&&(b=parseInt(b,10),k(b))})}var Sa={},pb=dc(r.domain,h.location.href,bc()),Ga=P(pb[0]),bb=
t(pb[1]),ya=t(pb[2]),Zb=!1,wb="GET",vb="application/x-www-form-urlencoded; charset=UTF-8",X=a||"",$b="",fb="",L=b||"",ta="",xa="",Ia,ac=r.title,ka="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),R=[Ga],Xb=[],Hb=[],Ib=[],z=500,ca,
Ua,ub,ja,Ka=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],La=["pk_kwd","piwik_kwd","utm_term"],xb="_pk_",oa,da,ia=!1,Fa,Ub,cb,Za=339552E5,Ja=18E5,Db=15768E6,Fb=!0,eb=0,Eb=!1,M=!1,gb,qa={},db={},pa={},J={},Z={},la=[],ua=!1,na=!1,Ma=!1,lb=!1,Va=!1,Da=fa(),Ea=null,ba,Qa,Ra,Xa=cc,yb;Ua=function(){if(Ea+ca<=(new Date).getTime()){var a=V("ping=1",null,"ping");T(a,z);return!0}return!1};(function(){var a,b,c={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",
wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"},d=h.devicePixelRatio||1;if(!/MSIE/.test(I.userAgent)){if(I.mimeTypes&&I.mimeTypes.length)for(a in c)Object.prototype.hasOwnProperty.call(c,a)&&(b=I.mimeTypes[c[a]],Z[a]=b&&b.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&g(I.javaEnabled)&&I.javaEnabled()&&(Z.java="1");W(h.GearsFactory)&&(Z.gears=
"1");Z.cookie=zb()}a=parseInt(ga.width,10)*d;d*=parseInt(ga.height,10);Z.res=parseInt(a,10)+"x"+parseInt(d,10)})();Wa();$a();Q("run",function(a,b){var c=null;if(m(a)&&!g(Sa[a])&&b){if(N(b))c=b;else if(m(b))try{eval("hookObj ="+b)}catch(d){}Sa[a]=c}return c});return{hook:Sa,getHook:function(a){return Sa[a]},getQuery:function(){return f},getContent:function(){return p},buildContentImpressionRequest:Pb,buildContentInteractionRequest:Aa,buildContentInteractionRequestNode:Qb,buildContentInteractionTrackingRedirectUrl:Jb,
getContentImpressionsRequestsFromNodes:Na,getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet:mb,trackCallbackOnLoad:Oa,trackCallbackOnReady:nb,buildContentImpressionsRequests:Ob,wasContentImpressionAlreadyTracked:Lb,appendContentInteractionToRequestIfPossible:Kb,setupInteractionsTracking:Nb,trackContentImpressionClickInteraction:Mb,internalIsNodeVisible:rb,isNodeAuthorizedToTriggerInteraction:jb,replaceHrefIfInternalLink:kb,getDomains:function(){return R},getConfigCookiePath:function(){return da},
getConfigDownloadExtensions:function(){return ka},enableTrackOnlyVisibleContent:function(a,b){return Yb(a,b,this)},clearTrackedContentImpressions:function(){la=[]},getTrackedContentImpressions:function(){return la},clearEnableTrackOnlyVisibleContent:function(){ua=!1},disableLinkTracking:function(){lb=Ma=!1},getConfigVisitorCookieTimeout:function(){return Za},getRemainingVisitorCookieTimeout:Bb,getVisitorId:function(){return Ha().uuid},getVisitorInfo:function(){return Ab()},getAttributionInfo:function(){return sa()},
getAttributionCampaignName:function(){return sa()[0]},getAttributionCampaignKeyword:function(){return sa()[1]},getAttributionReferrerTimestamp:function(){return sa()[2]},getAttributionReferrerUrl:function(){return sa()[3]},setTrackerUrl:function(a){X=a},getTrackerUrl:function(){return X},getSiteId:function(){return L},setSiteId:function(a){L=a;$a()},setUserId:function(a){g(a)&&a.length&&(ta=a,xa=Xa(ta).substr(0,16))},getUserId:function(){return ta},setCustomData:function(a,b){N(a)?ja=a:(ja||(ja={}),
ja[a]=b)},getCustomData:function(){return ja},setCustomRequestProcessing:function(a){gb=a},appendToTrackingUrl:function(a){fb=a},getRequest:function(a){return V(a)},addPlugin:function(a,b){S[a]=b},setCustomDimension:function(a,b){a=parseInt(a,10);0<a&&(g(b)||(b=""),m(b)||(b=String(b)),pa[a]=b)},getCustomDimension:function(a){a=parseInt(a,10);if(0<a&&Object.prototype.hasOwnProperty.call(pa,a))return pa[a]},deleteCustomDimension:function(a){a=parseInt(a,10);0<a&&delete pa[a]},setCustomVariable:function(a,
b,c,d){g(d)||(d="visit");g(b)&&(g(c)||(c=""),0<a&&(b=m(b)?b:String(b),c=m(c)?c:String(c),b=[b.slice(0,200),c.slice(0,200)],"visit"===d||2===d?(!1===M&&(M=Ya()),M[a]=b):"page"===d||3===d?qa[a]=b:"event"===d&&(db[a]=b)))},getCustomVariable:function(a,b){var c;g(b)||(b="visit");if("page"===b||3===b)c=qa[a];else if("event"===b)c=db[a];else if("visit"===b||2===b)!1===M&&(M=Ya()),c=M[a];return!g(c)||c&&""===c[0]?!1:c},deleteCustomVariable:function(a,b){this.getCustomVariable(a,b)&&this.setCustomVariable(a,
"","",b)},storeCustomVariablesInCookie:function(){Eb=!0},setLinkTrackingTimer:function(a){z=a},setDownloadExtensions:function(a){m(a)&&(a=a.split("|"));ka=a},addDownloadExtensions:function(a){var b;m(a)&&(a=a.split("|"));for(b=0;b<a.length;b++)ka.push(a[b])},removeDownloadExtensions:function(a){var b,c=[];m(a)&&(a=a.split("|"));for(b=0;b<ka.length;b++)-1===ea(a,ka[b])&&c.push(ka[b]);ka=c},setDomains:function(a){R=m(a)?[a]:a;a=!1;for(var b in R)if(Object.prototype.hasOwnProperty.call(R,b)&&k(Ga,P(String(R[b])))&&
(a=!0,!da)){a:{var c=R[b],d=bb;b=x(c);d=x(d);if(b&&"/"!==b&&d&&"/"!==d&&(c=P(c),!u(c,"/"))){v(b,"/")&&(b=String(b),b=b.substr(0,b.length-1));for(var e=b.split("/"),f=void 0,f=2;f<e.length;f++){var g=e.slice(0,f).join("/");if(u(c,g)){b=g;break}}if(l(d,b))break a}b=void 0}b&&this.setCookiePath(b);break}a||R.push(Ga)},setIgnoreClasses:function(a){Xb=m(a)?[a]:a},setRequestMethod:function(a){wb=a||"GET"},setRequestContentType:function(a){vb=a||"application/x-www-form-urlencoded; charset=UTF-8"},setReferrerUrl:function(a){ya=
a},setCustomUrl:function(a){var b=bb,c;qb(a)?Ia=a:"/"===a.slice(0,1)?Ia=qb(b)+"://"+ra(b)+a:(b=e(b),c=b.indexOf("?"),0<=c&&(b=b.slice(0,c)),c=b.lastIndexOf("/"),c!==b.length-1&&(b=b.slice(0,c+1)),Ia=b+a)},setDocumentTitle:function(a){ac=a},setAPIUrl:function(a){$b=a},setDownloadClasses:function(a){Hb=m(a)?[a]:a},setLinkClasses:function(a){Ib=m(a)?[a]:a},setCampaignNameKey:function(a){Ka=m(a)?[a]:a},setCampaignKeywordKey:function(a){La=m(a)?[a]:a},discardHashTag:function(a){ub=a},setCookieNamePrefix:function(a){xb=
a;M=Ya()},setCookieDomain:function(a){a=P(a);var b;d("test","testvalue",1E4,null,a);"testvalue"===c("test")?(d("test","",-86400,null,a),b=!0):b=!1;b&&(oa=a,Wa())},setCookiePath:function(a){da=a;Wa()},setVisitorCookieTimeout:function(a){Za=1E3*a},setSessionCookieTimeout:function(a){Ja=1E3*a},setReferralCookieTimeout:function(a){Db=1E3*a},setConversionAttributionFirstReferrer:function(a){cb=a},disableCookies:function(){ia=!0;Z.cookie="0";L&&ab()},deleteCookies:function(){ab()},setDoNotTrack:function(a){var b=
I.doNotTrack||I.msDoNotTrack;(Fa=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,b){Vb(a,b)},enableLinkTracking:function(a){lb=!0;ha?Wb(a):ma.push(function(){Wb(a)})},enableJSErrorTracking:function(){if(!Zb){Zb=!0;var a=h.onerror;h.onerror=function(b,c,d,e,f){O(function(){var a=c+":"+d;e&&(a+=":"+e);Rb("JavaScript Errors",a,b)});return a?a(b,c,d,e,f):!1}}},disablePerformanceTracking:function(){Fb=!1},setGenerationTimeMs:function(a){eb=parseInt(a,10)},enableHeartBeatTimer:function(a){a=
Math.max(a,1);ca=1E3*(a||15);null!==Ea&&sb()},disableHeartBeatTimer:function(){ba&&(clearTimeout(ba),ba=null);ca=null;window.removeEventListener("focus",aa);window.removeEventListener("blur",va)},killFrame:function(){h.location!==h.top.location&&(h.top.location=h.location)},redirectFile:function(a){"file:"===h.location.protocol&&(h.location=a)},setCountPreRendered:function(a){Ub=a},trackGoal:function(a,b,c){O(function(){var d=V("idgoal="+a+(b?"&revenue="+b:""),c,"goal");T(d,z)})},trackLink:function(a,
b,c,d){O(function(){Sb(a,b,c,d)})},trackPageView:function(a,b){la=[];C(L)?O(function(){H(X,$b,L)}):O(function(){var c=a||ac,c=c&&c.text?c.text:c;if(!m(c)){var d=r.getElementsByTagName("title");d&&g(d[0])&&(c=d[0].text)}c=V("action_name="+y(c),b,"log");T(c,z)})},trackAllContentImpressions:function(){C(L)||O(function(){nb(function(){var a=p.findContentNodes(),a=Na(a);Ca(a,z)})})},trackVisibleContentImpressions:function(a,b){C(L)||(g(a)||(a=!0),g(b)||(b=750),Yb(a,b,this),O(function(){Oa(function(){var a=
p.findContentNodes(),a=mb(a);Ca(a,z)})}))},trackContentImpression:function(a,b,c){!C(L)&&a&&(b=b||"Unknown",O(function(){var d=Pb(a,b,c);T(d,z)}))},trackContentImpressionsWithinNode:function(a){!C(L)&&a&&O(function(){ua?Oa(function(){var b=p.findContentNodesWithinNode(a),b=mb(b);Ca(b,z)}):nb(function(){var b=p.findContentNodesWithinNode(a),b=Na(b);Ca(b,z)})})},trackContentInteraction:function(a,b,c,d){!C(L)&&a&&b&&(c=c||"Unknown",O(function(){var e=Aa(a,b,c,d);T(e,z)}))},trackContentInteractionNode:function(a,
b){!C(L)&&a&&O(function(){var c=Qb(a,b);T(c,z)})},logAllContentBlocksOnPage:function(){var a=p.findContentNodes(),a=p.collectContent(a);void 0!==console&&console&&console.log&&console.log(a)},trackEvent:function(a,b,c,d,e){O(function(){Rb(a,b,c,d,e)})},trackSiteSearch:function(a,b,c,d){O(function(){var e=V("search="+y(a)+(b?"&search_cat="+y(b):"")+(g(c)?"&search_count="+c:""),d,"sitesearch");T(e,z)})},setEcommerceView:function(a,b,c,d){g(c)&&c.length?c instanceof Array&&(c=JSON2.stringify(c)):c="";
qa[5]=["_pkc",c];g(d)&&String(d).length&&(qa[2]=["_pkp",d]);if(g(a)&&a.length||g(b)&&b.length)g(a)&&a.length&&(qa[3]=["_pks",a]),g(b)&&b.length||(b=""),qa[4]=["_pkn",b]},addEcommerceItem:function(a,b,c,d,e){a.length&&(J[a]=[a,b,c,d,e])},trackEcommerceOrder:function(a,b,c,d,e,f){String(a).length&&g(b)&&Gb(a,b,c,d,e,f)},trackEcommerceCartUpdate:function(a){g(a)&&Gb("",a,"","","","")}}}var D,S={},r=document,I=navigator,ga=screen,h=window,G=h.performance||h.mozPerformance||h.msPerformance||h.webkitPerformance,
ha=!1,ma=[],y=h.encodeURIComponent,wa=h.decodeURIComponent,k,U,A,f={htmlCollectionToArray:function(a){var b=[],d;if(!a||!a.length)return b;for(d=0;d<a.length;d++)b.push(a[d]);return b},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return this.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var b,d,c=[];for(b=0;b<a.length;b++)d=this.find(a[b]),c=c.concat(d);return c=this.makeNodesUnique(c)},findNodesByTagName:function(a,b){if(!a||
!b||!a.getElementsByTagName)return[];var d=a.getElementsByTagName(b);return this.htmlCollectionToArray(d)},makeNodesUnique:function(a){var b=[].concat(a);a.sort(function(a,c){if(a===c)return 0;var d=ea(b,a),e=ea(b,c);return d===e?0:d>e?-1:1});if(1>=a.length)return a;var d=0,c=0,e=[],f;for(f=a[d++];f;)f===a[d]&&(c=e.push(d)),f=a[d++]||null;for(;c--;)a.splice(e[c],1);return a},getAttributeValueFromNode:function(a,b){if(this.hasNodeAttribute(a,b)){if(a&&a.getAttribute)return a.getAttribute(b);if(a&&
a.attributes&&"undefined"!==typeof a.attributes[b]){if(a.attributes[b].value)return a.attributes[b].value;if(a.attributes[b].nodeValue)return a.attributes[b].nodeValue;var d,c=a.attributes;if(c){for(d=0;d<c.length;d++)if(c[d].nodeName===b)return c[d].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,b){return!!this.getAttributeValueFromNode(a,b)},hasNodeAttribute:function(a,b){return a&&a.hasAttribute?a.hasAttribute(b):a&&a.attributes?"undefined"!==typeof a.attributes[b]:!1},hasNodeCssClass:function(a,
b){if(a&&b&&a.className){var d="string"===typeof a.className?a.className.split(" "):[];if(-1!==ea(d,b))return!0}return!1},findNodesHavingAttribute:function(a,b,d){d||(d=[]);if(!a||!b)return d;a=va(a);if(!a||!a.length)return d;var c,e;for(c=0;c<a.length;c++)e=a[c],this.hasNodeAttribute(e,b)&&d.push(e),d=this.findNodesHavingAttribute(e,b,d);return d},findFirstNodeHavingAttribute:function(a,b){if(a&&b){if(this.hasNodeAttribute(a,b))return a;var d=this.findNodesHavingAttribute(a,b);if(d&&d.length)return d[0]}},
findFirstNodeHavingAttributeWithValue:function(a,b){if(a&&b){if(this.hasNodeAttributeWithValue(a,b))return a;var d=this.findNodesHavingAttribute(a,b);if(d&&d.length){var c;for(c=0;c<d.length;c++)if(this.getAttributeValueFromNode(d[c],b))return d[c]}}},findNodesHavingCssClass:function(a,b,d){d||(d=[]);if(!a||!b)return d;if(a.getElementsByClassName)return b=a.getElementsByClassName(b),this.htmlCollectionToArray(b);a=va(a);if(!a||!a.length)return[];var c,e;for(c=0;c<a.length;c++)e=a[c],this.hasNodeCssClass(e,
b)&&d.push(e),d=this.findNodesHavingCssClass(e,b,d);return d},findFirstNodeHavingClass:function(a,b){if(a&&b){if(this.hasNodeCssClass(a,b))return a;var d=this.findNodesHavingCssClass(a,b);if(d&&d.length)return d[0]}},isLinkElement:function(a){if(!a)return!1;a=String(a.nodeName).toLowerCase();return-1!==ea(["a","area"],a)},setAnyAttribute:function(a,b,d){a&&b&&(a.setAttribute?a.setAttribute(b,d):a[b]=d)}},p={CONTENT_ATTR:"data-track-content",CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",
CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",location:void 0,findContentNodes:function(){return f.findMultiple(["."+this.CONTENT_CLASS,"["+this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var b=f.findNodesHavingCssClass(a,this.CONTENT_CLASS),
d=f.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(d&&d.length){var c;for(c=0;c<d.length;c++)b.push(d[c])}f.hasNodeAttribute(a,this.CONTENT_ATTR)?b.push(a):f.hasNodeCssClass(a,this.CONTENT_CLASS)&&b.push(a);return b=f.makeNodesUnique(b)},findParentContentNode:function(a){if(a)for(var b=0;a&&a!==r&&a.parentNode;){if(f.hasNodeAttribute(a,this.CONTENT_ATTR)||f.hasNodeCssClass(a,this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<b)break;b++}},findPieceNode:function(a){var b;(b=f.findFirstNodeHavingAttribute(a,
this.CONTENT_PIECE_ATTR))||(b=f.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return b?b:a},findTargetNodeNoDefault:function(a){if(a){var b=f.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(b||(b=f.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(b=f.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return b}},findTargetNode:function(a){var b=this.findTargetNodeNoDefault(a);return b?b:a},findContentName:function(a){if(a){var b=f.findFirstNodeHavingAttributeWithValue(a,
this.CONTENT_NAME_ATTR);if(b)return f.getAttributeValueFromNode(b,this.CONTENT_NAME_ATTR);if(b=this.findContentPiece(a))return this.removeDomainIfIsInLink(b);if(f.hasNodeAttributeWithValue(a,"title"))return f.getAttributeValueFromNode(a,"title");b=this.findPieceNode(a);if(f.hasNodeAttributeWithValue(b,"title"))return f.getAttributeValueFromNode(b,"title");a=this.findTargetNode(a);if(f.hasNodeAttributeWithValue(a,"title"))return f.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var b=
f.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(b)return f.getAttributeValueFromNode(b,this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var b=this.findTargetNode(a);if(f.hasNodeAttributeWithValue(b,this.CONTENT_TARGET_ATTR))return f.getAttributeValueFromNode(b,this.CONTENT_TARGET_ATTR);if(f.hasNodeAttributeWithValue(b,"href"))return a=f.getAttributeValueFromNode(b,"href"),this.toAbsoluteUrl(a);
a=this.findPieceNode(a);if(f.hasNodeAttributeWithValue(a,"href"))return a=f.getAttributeValueFromNode(a,"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var b=
a.nodeName.toLowerCase();if(-1!==ea(["img","embed","video","audio"],b)&&f.findFirstNodeHavingAttributeWithValue(a,"src"))return a=f.findFirstNodeHavingAttributeWithValue(a,"src"),f.getAttributeValueFromNode(a,"src");if("object"===b&&f.hasNodeAttributeWithValue(a,"data"))return f.getAttributeValueFromNode(a,"data");if("object"===b){if((b=f.findNodesByTagName(a,"param"))&&b.length){var d;for(d=0;d<b.length;d++)if("movie"===f.getAttributeValueFromNode(b[d],"name")&&f.hasNodeAttributeWithValue(b[d],"value"))return f.getAttributeValueFromNode(b[d],
"value")}if((a=f.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},trim:function(a){return a&&String(a)===a?a.replace(/^\s+|\s+$/g,""):a},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var b=a.getBoundingClientRect(),d=r.documentElement||{},c=0>b.top;c&&a.offsetTop&&(c=0<a.offsetTop+b.height);a=d.clientWidth;h.innerWidth&&a>h.innerWidth&&(a=h.innerWidth);d=d.clientHeight;h.innerHeight&&d>h.innerHeight&&(d=h.innerHeight);return(0<
b.bottom||c)&&0<b.right&&b.left<a&&(b.top<d||c)},isNodeVisible:function(a){var b=rb(a);a=this.isOrWasNodeInViewport(a);return b&&a},buildInteractionRequestParams:function(a,b,d,c){var e="";a&&(e+="c_i="+y(a));b&&(e&&(e+="&"),e+="c_n="+y(b));d&&(e&&(e+="&"),e+="c_p="+y(d));c&&(e&&(e+="&"),e+="c_t="+y(c));return e},buildImpressionRequestParams:function(a,b,d){a="c_n="+y(a)+"&c_p="+y(b);d&&(a+="&c_t="+y(d));return a},buildContentBlock:function(a){if(a){var b=this.findContentName(a),d=this.findContentPiece(a);
a=this.findContentTarget(a);b=this.trim(b);d=this.trim(d);a=this.trim(a);return{name:b||"Unknown",piece:d||"Unknown",target:a||""}}},collectContent:function(a){if(!a||!a.length)return[];var b=[],d,c;for(d=0;d<a.length;d++)c=this.buildContentBlock(a[d]),g(c)&&b.push(c);return b},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||h.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===
a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=this.toAbsoluteUrl(a);if(!a)return!1;var b=this.getLocation().origin;return b===a?!0:0===String(a).indexOf(b)?
":"===String(a).substr(b.length,1)?!1:!0:!1},setHrefAttribute:function(a,b){a&&b&&f.setAnyAttribute(a,"href",b)},shouldIgnoreInteraction:function(a){var b=f.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=f.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return b||a}};F(h,"beforeunload",function(){var a;Q("unload");if(D){do a=new Date;while(a.getTimeAlias()<D)}},!1);(function(){var a;r.addEventListener?F(r,"DOMContentLoaded",function d(){r.removeEventListener("DOMContentLoaded",
d,!1);E()}):r.attachEvent&&(r.attachEvent("onreadystatechange",function d(){"complete"===r.readyState&&(r.detachEvent("onreadystatechange",d),E())}),r.documentElement.doScroll&&h===h.top&&function c(){if(!ha){try{r.documentElement.doScroll("left")}catch(a){setTimeout(c,0);return}E()}}());/WebKit/.test(I.userAgent)&&(a=setInterval(function(){if(ha||/loaded|complete/.test(r.readyState))clearInterval(a),E()},10));F(h,"load",E,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;k=new B;_paq=function(a,
b){var d={},c,e;for(c=0;c<b.length;c++){var f=b[c];d[f]=1;for(e=0;e<a.length;e++)if(a[e]&&a[e][0]){var g=a[e][0];f===g&&(x(a[e]),delete a[e],1<d[g]&&void 0!==console&&console&&console.error&&console.error("The method "+g+' is registered more than once in "paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/guides/tracking-javascript-guide#multiple-piwik-trackers'),d[g]++)}}return a}(_paq,"disableCookies setTrackerUrl setAPIUrl setCookiePath setCookieDomain setDomains setUserId setSiteId enableLinkTracking".split(" "));
for(U=0;U<_paq.length;U++)_paq[U]&&x(_paq[U]);_paq=new function(){return{push:x}};A={addPlugin:function(a,b){S[a]=b},getTracker:function(a,b){g(b)||(b=this.getAsyncTracker().getSiteId());g(a)||(a=this.getAsyncTracker().getTrackerUrl());return new B(a,b)},getAsyncTracker:function(){return k}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return A});return A}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();
(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=GaoTracker)})();
"function"!==typeof GaoTracker_log&&(GaoTracker_log=function(t,g,W,N){function m(g){try{if(window["piwik_"+g])return window["piwik_"+g]}catch(m){}}var w=GaoTracker.getTracker(W,g);w.setDocumentTitle(t);w.setCustomData(N);(t=m("tracker_pause"))&&w.setLinkTrackingTimer(t);(t=m("download_extensions"))&&w.setDownloadExtensions(t);(t=m("hosts_alias"))&&w.setDomains(t);(t=m("ignore_classes"))&&w.setIgnoreClasses(t);w.trackPageView();m("install_tracker")&&(piwik_track=function(g,m,t,E){w.setSiteId(m);w.setTrackerUrl(t);
w.trackLink(g,E)},w.enableLinkTracking())});
